### ISSUE TITLE
About dependency

### ISSUE THREAD

**Issue by hailsong** [bharat-b7/RVH_Mesh_Registration#17]
Hello, I found this repository to registration my scan data to SMPL body model.
To using this code, I create conda environment with attached requirement.txt file, but I got this message.

> (base) root@b84ceda4246b:~/Dataset/RVH_Mesh_Registration# conda create --name rvh_env --file requirements.txt 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - tqdm==4.61.2=pyhd8ed1ab_1
>   - ffmpeg==4.3=hf484d3e_0
>   - pytorch==1.7.1=cpu_py37hf1c21f6_2
>   - libgfortran-ng==9.3.0=hff62375_19
>   - llvm-openmp==12.0.1=h4bd325d_0
>   - pyyaml==5.4.1=py37h5e8e339_0
>   - libgcc-ng==9.3.0=h2828fa1_19
>   - torchvision==0.8.2=py37h6dc5373_1_cpu
>   - tabulate==0.8.9=pyhd8ed1ab_0
>   - jpeg==9d=h36c2ea0_0
>   - termcolor==1.1.0=py_2
>   - iopath==0.1.9=py37
>   - libcblas==3.9.0=8_mkl
>   - mkl==2020.4=h726a3e6_304
>   - portalocker==1.7.0=py37h89c1867_1
>   - yacs==0.1.6=py_0
>   - pytorch3d==0.4.0=py37_cu102_pyt171
>   - libgomp==9.3.0=h2828fa1_19
>   - fvcore==0.1.5.post20210719=py37
>   - _libgcc_mutex==0.1=conda_forge
>   - scikit-learn==0.24.2=py37h18a542f_0
>   - libblas==3.9.0=8_mkl
>   - scipy==1.7.0=py37h29e03ee_1
>   - libgfortran5==9.3.0=hff62375_19
>   - threadpoolctl==2.2.0=pyh8a188c0_0
>   - python_abi==3.7=2_cp37m
>   - libstdcxx-ng==9.3.0=h6de172a_19
>   - nvidiacub==1.10.0=0
>   - _openmp_mutex==4.5=1_llvm
>   - yaml==0.2.5=h516909a_0
>   - joblib==1.0.1=pyhd8ed1ab_0
>   - mkl-service==2.3.0=py37h8f50634_2
>   - liblapack==3.9.0=8_mkl
>   - trimesh==3.9.23=pyh6c4a22f_0
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

I think linux-64's channel is enough to install these packages, but I wanna check if they need additional channels.
Also, I wonder, is there any specific environment setting needed to use this code? (Guessing with pytorch3d==0.4.0=py37_cu102_pyt171 .....)
If specific cuda version or python version is required, I should make environment with docker.

Thank you!

**Comment by jizhu1023** [comment]
The following command solve this problem:
`while read requirement; do conda install ----channel "conda-forge" yes $requirement || pip install $requirement; done < requirements.txt`

**Comment by Atharva-Peshkar** [comment]
Same issue.

**Comment by hailsong** [comment]
Thank you for updating requirements file!
